### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContextBuilder.protocols([Ljava/lang/String;)

### ISSUE THREAD

**Issue by pauloangelo** [razem-io/scala-influxdb-client#6]
Hi,

I'm getting the error below. 

```
Exception in thread "main" java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContextBuilder.protocols([Ljava/lang/String;)Lio/netty/handler/ssl/SslContextBuilder;
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.buildSslContext(DefaultSslEngineFactory.java:45)
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.init(DefaultSslEngineFactory.java:73)
	at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:101)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:89)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:71)
	at io.razem.influxdbclient.HttpClient.<init>(HttpClient.scala:23)
	at io.razem.influxdbclient.InfluxDB$.connect(InfluxDB.scala:16)
```

Dependencies:

```
io.razem#scala-influxdb-client_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found io.razem#scala-influxdb-client_2.11;0.6.2 in central
	found org.asynchttpclient#async-http-client;2.10.4 in central
	found org.asynchttpclient#async-http-client-netty-utils;2.10.4 in central
	found io.netty#netty-buffer;4.1.42.Final in central
	found io.netty#netty-common;4.1.42.Final in central
	found org.slf4j#slf4j-api;1.7.26 in spark-list
	found com.sun.activation#javax.activation;1.2.0 in central
	found io.netty#netty-codec-http;4.1.42.Final in central
	found io.netty#netty-transport;4.1.42.Final in central
	found io.netty#netty-resolver;4.1.42.Final in central
	found io.netty#netty-codec;4.1.42.Final in central
	found io.netty#netty-handler;4.1.42.Final in central
	found io.netty#netty-codec-socks;4.1.42.Final in central
	found io.netty#netty-handler-proxy;4.1.42.Final in central
	found io.netty#netty-transport-native-epoll;4.1.42.Final in central
	found io.netty#netty-transport-native-unix-common;4.1.42.Final in central
	found io.netty#netty-transport-native-kqueue;4.1.42.Final in central
	found io.netty#netty-resolver-dns;4.1.42.Final in central
	found io.netty#netty-codec-dns;4.1.42.Final in central
	found org.reactivestreams#reactive-streams;1.0.2 in spark-list
	found com.typesafe.netty#netty-reactive-streams;2.0.3 in central
	found io.spray#spray-json_2.11;1.3.5 in central
:: resolution report :: resolve 586ms :: artifacts dl 11ms
	:: modules in use:
	com.sun.activation#javax.activation;1.2.0 from central in [default]
	com.typesafe.netty#netty-reactive-streams;2.0.3 from central in [default]
	io.netty#netty-buffer;4.1.42.Final from central in [default]
	io.netty#netty-codec;4.1.42.Final from central in [default]
	io.netty#netty-codec-dns;4.1.42.Final from central in [default]
	io.netty#netty-codec-http;4.1.42.Final from central in [default]
	io.netty#netty-codec-socks;4.1.42.Final from central in [default]
	io.netty#netty-common;4.1.42.Final from central in [default]
	io.netty#netty-handler;4.1.42.Final from central in [default]
	io.netty#netty-handler-proxy;4.1.42.Final from central in [default]
	io.netty#netty-resolver;4.1.42.Final from central in [default]
	io.netty#netty-resolver-dns;4.1.42.Final from central in [default]
	io.netty#netty-transport;4.1.42.Final from central in [default]
	io.netty#netty-transport-native-epoll;4.1.42.Final from central in [default]
	io.netty#netty-transport-native-kqueue;4.1.42.Final from central in [default]
	io.netty#netty-transport-native-unix-common;4.1.42.Final from central in [default]
	io.razem#scala-influxdb-client_2.11;0.6.2 from central in [default]
	io.spray#spray-json_2.11;1.3.5 from central in [default]
	org.asynchttpclient#async-http-client;2.10.4 from central in [default]
	org.asynchttpclient#async-http-client-netty-utils;2.10.4 from central in [default]
	org.reactivestreams#reactive-streams;1.0.2 from spark-list in [default]
	org.slf4j#slf4j-api;1.7.26 from spark-list in [default]
```

Thanx in advance.

**Comment by pauloangelo** [comment]
I was submitting to Apache Spark version 2.2.0. Using version 2.4.4 is running. Spark has a netty-XXX.jar.
